import Head from 'next/head'
import { useState } from 'react'
import Link from 'next/link'
import styles from './header.module.css'
import Router from 'next/router'

export default function Header() {
    const [searchTerm, setSearchTerm] = useState('')

    const handleSearch = () => {
        Router.push(`/search?term=${searchTerm}`)
    }
    const handleKeyDown = (e) => {
        if (e.key === 'Enter')
            handleSearch()
    }
    return (
        <>
            <Head>
                <title>Movies Database</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.header}>
                <Link href='/' passHref>
                    <h2>
                        Movies DB
                    </h2>
                </Link>
                <div className={styles.search}>
                    <input
                        type="text"
                        value={searchTerm}
                        placeholder='Search for your favourite film'
                        onChange={(e) => setSearchTerm(e.target.value)}
                        onKeyDown={handleKeyDown}
                    />
                    <button type="button" onClick={handleSearch}>Search</button>
                </div>
            </div>
        </>
    )
}